### ISSUE TITLE
swc-plugin-coverage-instrument incompatible with middleware

### ISSUE THREAD

**Issue by cers** [kwonoj/swc-plugin-coverage-instrument#248]
## Steps to reproduce:

1. run `npx create-next-app minimal-reproduction --typescript --eslint --no-tailwind --no-src-dir --app --import-alias '@/*'`
2. run `npm i -D swc-plugin-coverage-instrument`
3. add plugin to `next.config.mjs`:
```
const nextConfig = {
    experimental: {
        swcPlugins: [['swc-plugin-coverage-instrument', {}]]
    }
}
export default nextConfig;
```
4. clean up `layout.tsx` to avoid other compilation issues
```
export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (<html lang="en"><body>{children}</body></html>);
}
```
5. create `middleware.ts`
```
import { NextResponse } from 'next/server'
export async function middleware() {
    return NextResponse.next()
}
```
6. run `npm run build`
7. run `npm start`
8. visit http://localhost:3000

## Result
First a code dump, and then many errors like:

```
EvalError: Code generation from strings disallowed for this context
    at new Function (<anonymous>)
    at j (/Users/christian/Projects/minimal-reproduction/.next/server/middleware.js:13:1314)
    at 841 (/Users/christian/Projects/minimal-reproduction/.next/server/middleware.js:13:28509)
    at t (/Users/christian/Projects/minimal-reproduction/.next/server/edge-runtime-webpack.js:1:127)
    at /Users/christian/Projects/minimal-reproduction/.next/server/middleware.js:13:119656
    at r (/Users/christian/Projects/minimal-reproduction/.next/server/edge-runtime-webpack.js:1:1169)
    at /Users/christian/Projects/minimal-reproduction/.next/server/middleware.js:1:51
    at Script.runInContext (node:vm:148:12)
    at runInContext (node:vm:300:6)
    at evaluateInContext (/Users/christian/Projects/minimal-reproduction/node_modules/next/dist/server/web/sandbox/context.js:407:38)
/Users/christian/Projects/minimal-reproduction/.next/server/middleware.js:2
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`}process!==n.g.process&&(process.env=n.g.process.env,n.g.process=process),Object.defineProperty(globalThis,"__import_unsupported",{value:function(e){let t=new Proxy(function(){},{get(t,n){if("then"===n)return{};throw Error(_(e))},construct(){throw Error(_(e))},apply(n,r,i){if("function"==typeof i[0])return i[0](t);throw Error(_(e))}});return new Proxy({},{get:()=>t})},enumerable:!1,configurable:!1}),w();class y extends Error{constructor({page:e}){super(`The middleware "${e}" accepts an async API directly with the form:
                                                                                                                                                          ^

TypeError: Cannot redefine property: __import_unsupported
    at Proxy.defineProperty (<anonymous>)
    at 841 (/Users/christian/Projects/minimal-reproduction/.next/server/middleware.js:2:155)
    at t (/Users/christian/Projects/minimal-reproduction/.next/server/edge-runtime-webpack.js:1:127)
    at /Users/christian/Projects/minimal-reproduction/.next/server/middleware.js:13:119656
    at r (/Users/christian/Projects/minimal-reproduction/.next/server/edge-runtime-webpack.js:1:1169)
    at /Users/christian/Projects/minimal-reproduction/.next/server/middleware.js:1:51
    at Script.runInContext (node:vm:148:12)
    at runInContext (node:vm:300:6)
    at evaluateInContext (/Users/christian/Projects/minimal-reproduction/node_modules/next/dist/server/web/sandbox/context.js:407:38)
    at getRuntimeContext (/Users/christian/Projects/minimal-reproduction/node_modules/next/dist/server/web/sandbox/sandbox.js:71:9)
/Users/christian/Projects/minimal-reproduction/.next/server/middleware.js:2
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime`}process!==n.g.process&&(process.env=n.g.process.env,n.g.process=process),Object.defineProperty(globalThis,"__import_unsupported",{value:function(e){let t=new Proxy(function(){},{get(t,n){if("then"===n)return{};throw Error(_(e))},construct(){throw Error(_(e))},apply(n,r,i){if("function"==typeof i[0])return i[0](t);throw Error(_(e))}});return new Proxy({},{get:()=>t})},enumerable:!1,configurable:!1}),w();class y extends Error{constructor({page:e}){super(`The middleware "${e}" accepts an async API directly with the form:
```

**Comment by kwonoj** [comment]
https://github.com/kwonoj/swc-plugin-coverage-instrument/issues/226
